export const CHANGE_VOTE_FAIL = 'CHANGE_VOTE_FAIL'
export const CHANGE_VISIBLE_FAIL = 'CHANGE_VISIBLE_FAIL'
export const CHANGE_SONGS_FILTER = 'CHANGE_SONGS_FILTER'
export const RESET_ALL_VOTES = 'RESET_ALL_VOTES'
